imports:
  - { resource: 'listeners.yaml' }
  - { resource: 'events.yaml' }
  - { resource: 'kernel.yaml' }
  - { resource: 'controllers.yaml' }
  - { resource: 'routing.yaml' }
  - { resource: 'twig.yaml' }
  - { resource: 'console.yaml' }